### ISSUE TITLE
[Feature Request]:- Enable Shell completions

### ISSUE THREAD

**Issue by Enigma1309** [kRHYME7/Hyde-cli#21]
Title says it all,
Hyprdots-ctl is a good tool for a lot of stuff  but sometimes i miss shell completions, i have to use `help` flag for the minor tasks, and sometimes habitually i hit [TAB] key that shows up the working directory file listings (lol)...
shell completions should be a good add-on in my opinion

**Comment by kRHYME7** [comment]
😄 how I wish... 

Anyone is open for PR on this.

**Comment by kRHYME7** [comment]
Additional Notes.

``` Hyde  man ``` Will provide the command tree with description, this can be used for Shell completions. 

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/c1744db1-a005-4898-9356-168b3b53d48a)

**Comment by Enigma1309** [comment]
yeah i know about it , i'll try to work on completions (and few other stuff) after my exams but don't take my words seriously  :)

**Comment by kRHYME7** [comment]
Reporting bugs should be helpful too.

**Comment by kRHYME7** [comment]
@Enigma1309   add ` source /usr/share/hyde-cli/Hyde.zsh ` at ./.zshrc if shell completion is not working on zsh

**Comment by Enigma1309** [comment]
Thanks it worked, i'm busy a bit but thanks @kRHYME7 and @rubiin for making this work.
you guys may open a pr in the Hyprdots repo

**Comment by rubiin** [comment]
I have also added this on the readme under FAQ so other people can quicky troubleshoot it

> @Enigma1309 add `source /usr/share/hyde-cli/Hyde.zsh` at ./.zshrc if shell completion is not working on zsh
