### ISSUE TITLE
Pastebin rofi theme error & Auto waybar kill on pasting

### ISSUE THREAD

**Issue by Enigma1309** [kRHYME7/Hyde-cli#22]
Theme error on command 'Hyprdots show pastebin {flag}'

- `Hyprdots show pastebin w`
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/4ebeb62f-c6e2-4300-a0ba-289d2dfe276b)

- `Hyprdots show pastebin d`
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/4786c6a5-deb5-46de-a573-722d77855e70)

- `Hyprdots show pastebin c`
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/44495b11-e77c-4d45-8a48-fd02babd264e)

---

Normally it cliphist.sh works but not the Hyprdots one

![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/118104b5-7902-4ed3-8626-08fcd58709fe)

**Comment by Enigma1309** [comment]
Also this happens with emoji keyboard too

**Comment by Enigma1309** [comment]
Thanks..it works now, but kills the waybar when choosing the emoji or escaping it.

**Comment by kRHYME7** [comment]
can you provide logs for both while running on the terminal?

**Comment by Enigma1309** [comment]
it shows no logs in terminal, also i forgot to mention this happens on emoji pallet

**Comment by Enigma1309** [comment]
i found that this usually happens when the firefox/librewolf are in focus. 😩
Here's a recording,

https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/521ab833-0bc3-4574-875b-9407f5672af0

- i did run the command and the pallet showed
- i presssed enter and the waybar got killed (mind that emoji did not get pasted)
- i manually pasted the emoji (usig ctrl+v) and the respawned the waybar (using ctrl+esc keybind)

**Comment by kRHYME7** [comment]
@Enigma1309  I think this is due to killing of ` wtype ` (the one that makes pasting possible)

Does the issue exist if you use the Pastebin also?

**Comment by kRHYME7** [comment]
Hmm I tried it on 2 different systems and I can't replicate it. 

I recently removed all the funtion to kill wtype, Please try it.
``` yay -Sy hyprdots-ctl-git  ```

**Comment by Enigma1309** [comment]
no luck here :(

**Comment by kRHYME7** [comment]
can you try to run waybar on the terminal too. see the errors waybar might output

**Comment by Enigma1309** [comment]
it just kill it after choosing emoji
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/222f6bbf-f127-4cde-b409-4ce3632ab188)

**Comment by kRHYME7** [comment]
``` ❯ yay -Qs waybar
local/waybar 0.10.0-3
    Highly customizable Wayland bar for Sway and Wlroots based compositors
```

This is my waybar version. Can't really replicate this, so I will wait for more info/symptoms.

All I know for now is waybar receives and exits status same as ``` killall waybar ``` 

I'll try to review the script later

**Comment by Enigma1309** [comment]
i'm on the same version too , hope it gets refactored soon

**Comment by kRHYME7** [comment]
If you have some time, please try to test other rofi launchers. Thanks

**Comment by kRHYME7** [comment]
Can you try to run this? ``` wtype -M ctrl v -m ctrl  ```

**Comment by Enigma1309** [comment]
i'm on latest version of hyprdors-ctl-git  and `wtype -M ctrl v -m ctrl ` kill waybar instantly without any log

**Comment by kRHYME7** [comment]
Okay actually this ``` wtype -M ctrl v -m ctrl ``` is the reason we can paste.  Do you happen to have a key bind similar to ``` ctrl + v ``` ? 

Did this happen only recently? 

wtype -M ctrl shift v -m ctrl wtype -M ctrl v -m ctrl 😄

**Comment by Enigma1309** [comment]
> Do you happen to have a key bind similar to ctrl + v ?

Nope, i don't

> Did this happen only recently?

Nah i've been experiencing this for a long time, it usually happens on firefox/librewolf, but the following commands kill them despite being on such browser.

>  wtype -M ctrl v -m ctrl
 wtype -M ctrl V -m ctrl  
 wtype -M ctrl v -m ctrl -d 2000 
 wtype -M ctrl V -m ctrl -d 2000

All of them kills waybar instantly :(

so it mean it's an issue with wtype..

---

`Hyprdots show pastebin c ` also shows the same behaviour but $scrDir/cliphist.sh don't..

**Comment by kRHYME7** [comment]
> Hyprdots show pastebin c also shows the same behaviour but $scrDir/cliphist.sh don't..

Because we are attempting to paste it using virtual keyboard.  

This happens every time ?

**Comment by Enigma1309** [comment]
> wtype -M ctrl c -m ctrl and  wtype -M ctrl V

Still kills waybar..


> This happens every time ?

Unfortunately, yes (in firefox and it's derivates) but i can't reproduce it in brave..

> Ping me at discord

ok, i'll do when i'll be free

**Comment by kRHYME7** [comment]
I see! So basically it works on others except Firefox derivatives? 

For now should we disable the pasting on firefox/librewolf ?

**Comment by Enigma1309** [comment]
> For now should we disable the pasting on firefox/librewolf ?

that would be okay :D

**Comment by kRHYME7** [comment]
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/39e8fa0e-e850-4e3d-866b-bbde688432be)

@Enigma1309  run only once

``` Hyprdots show pastebin -c --ignore=LibreWolf ``` 

This is share with 'pastebin' 'emoji' and glyph so just invoke this once.

**Comment by Enigma1309** [comment]
i think it didn't ran correctly 
![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/94917588/3a563643-dc7d-4a30-8dd8-abb2be6355c8)

**Comment by kRHYME7** [comment]
My bad ``` Hyprdots show pastebin c --ignore=LibreWolf ```

remove '-'

**Comment by Enigma1309** [comment]
okay thanks, it worked, although i have to manually paste emojis but it's better than relaunching waybar and pasting, closing this as completed 
thanks

**Comment by Enigma1309** [comment]
hey i found out that it's killing way-bar on a lot of other apps too, i can technically add them to ignore list but that won't be a good solution to problem, can we change the source code of emoji pasting to `wtype <text>` since it's not killing the way-bar anymore..
i found this out when looking at the source code of wofi-emoji it's using the same approach... and it's not killing the way-bar on any apps fortunately :)

**Comment by kRHYME7** [comment]
Sure! But wtype <text> got some more problem though. It is not suited to paste some codes(especial characters), that's why I resort to emulating the keyboard shortcut. Will try to use wtype <text> . I'm just too clueless on why I don't get this issues. 

Will change this later

**Comment by Enigma1309** [comment]
if wofi-emoji was using it then i guess it should be fine for pasting emojis or maybe we can pass extra argument to use wtpe explicitly like :- `hyde show emoji --wtype`

**Comment by kRHYME7** [comment]
> if wofi-emoji was using it then i guess it should be fine for pasting emojis or maybe we can pass extra argument to use wtpe explicitly like :- hyde show emoji --wtype

For emojis will use wtype <TEXT\>  as the especial characters are at minimum

For full string, I will test it again if it's really safe, I tried to paste a full code on browser ending up crashing my system.

**Comment by kRHYME7** [comment]
BTW, can you confirm if it crashes way bar when you paste text inside  code editor too? Would still want to emulate pasting if I'm using code editor as it wouldn't break the text

**Comment by Enigma1309** [comment]
i've been using `cliphist.sh c` for pastebin and it works everywhere ,
i don't really use `Hyde show pastebin c` but after trying it i found that it crashes the waybar too like Code-OSS, it doesn't affect nvim as there's yanking and putting keybinding (makes sense)

---

My real concern is emoji keyboard as it's crashing waybar on a lot of applications

**Comment by kRHYME7** [comment]
can you try it now?

**Comment by Enigma1309** [comment]
tysm it's working now ❤️

**Comment by kRHYME7** [comment]
I have a questions, does it work on vencord?

**Comment by kRHYME7** [comment]
@Enigma1309  Hello, I have a favor to ask. Can you try to emulate pasting using this command ` hyprctl dispatch exec 'wtype -M ctrl v -m ctrl' ` this way it is run through hyprland's envs.  You should probably add it as a key bind to work

**Comment by Enigma1309** [comment]
i just found out that instead of killing way-bar it's toggling way-bar 

> `hyprctl dispatch exec 'wtype -M ctrl v -m ctrl'` 

this command also do the same thing


here's a screen recording just in case

https://github.com/kRHYME7/Hyde-cli/assets/94917588/d180f75a-dd14-47e4-ba53-bbabdb7bb32f

**Comment by kRHYME7** [comment]
So strange why waybar receives those Signals

In my case I don't have this as I do have custom keybindings. 
![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/7660c9aa-5eed-4afd-8e21-ad
ed230dfe87)

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/87607767-795b-44df-8be4-c3afd44f5d00)

 
Can you try to disable any waybar related keybindings?  To check if you totally unset it run ` keybinds_hint.sh -j | grep waybar ` it should return nothing

**Comment by Enigma1309** [comment]
![image](https://github.com/kRHYME7/Hyde-cli/assets/94917588/adaf3f77-9fec-4050-82a4-ea002f60db17)


after disabling the  `ctrl+escape` keybind... i found that it no longer despawns the waybar....
(this was the default binding in hyprdots)

![image](https://github.com/kRHYME7/Hyde-cli/assets/94917588/269e122d-04ba-43ec-9b47-a588b09b9b84)




does it means that somehow wtype is emulating ctrl+escape..?

---

after researching a bit i found out that it doesn't work the same way....
![image](https://github.com/kRHYME7/Hyde-cli/assets/94917588/2ae89c2b-51eb-4dad-85c6-4e41b2fa0fed)

it clearly types `ctrl+v` i don't get the actual issue here..

---

anyways, i think it should work well without that keybind being enabled.
also should we address this issue to hyprdots/tittu ? or maybe create a pr?

**Comment by kRHYME7** [comment]
Thanks! Can you do the PR on the main repo?

This PR is added by a contributor, so I hope Tittu will be fine with it changing it to something. 
![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/4f7f393c-bd6e-4463-ad49-165f968ecf98)

What actually triggers it is the ` Press ctrl` `press v` this triggers the same as `Press ctrl` `Press escape`.  Maybe it's either hyprland or wtype bug I guess. ( e.g some keys can trigger the lid switch which in the past is linked to a keybind that locks and suspends the system  ).

**Comment by Enigma1309** [comment]
> This means setting ctrl + esc might be not a good Idea.

okay i'm creating a pr and will be linking this issue.
