### ISSUE TITLE
Hyprdots wallbash disable no longer works

### ISSUE THREAD

**Issue by Radrahil** [kRHYME7/Hyde-cli#26]
Hyde wallbash toggle 0 gives this
```
which: no globalcontrol.sh in (/home/rahil/.local/bin:/home/rahil/.cargo/bin:/home/rahil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/rahil/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/usr/lib/hyde-cli/:/usr/bin)
dirname: missing operand
Try 'dirname --help' for more information.
/usr/lib/hyde-cli/GLOBAL_hyde: line 392: /globalcontrol.sh: No such file or directory
mkdir: cannot create directory ‘’: No such file or directory
Hyde-cli created a directory: 
/usr/lib/hyde-cli/GLOBAL_hyde: line 113: /home/rahil/.cache/hyde-cli/hyde.meta: No such file or directory
Sourcing /home/rahil/.cache/hyde-cli/hyde.meta failed.
 You might not install this using the hyde-cli
Do not worry you can follow the instructions below to manage hyde configuration
=======================================================================================
Please run:
           'Hyde-install'                                 Install Hyde (default)
For advanced usage see options below
        -l|--link                                                Flag to transfer the link to a Clone Directory
                                                                    ﯦ This is useful if you already have a Hyde
                                                                    Default: 'false'
        -d|--dir ~/custom/Hyde/directory                      Clone Hyde in a Custom path then run installation.
                                                                Default: '/home/rahil/.cache/hyde-cli/Hyde'
        -g|--git https://gitclone/link/                          Upstream repository link to be cloned
                                                                Default: 'https://github.com/prasanthrangan/hyprdots'
[ TIP] Looks like you already have a clone directory somewhere
      To reuse that clone directory run 'Hyde-install -d /home/rahil/custom/Hyde/directory --link'
      Then 'Hyde-cli' will remember this directory 

```
I already have Hyprdots installed back when this repo was named Hyprdotscli, what do I do? A migration tab would be useful

**Comment by kRHYME7** [comment]
that means you need to have the Hyde branch installed. FYI the hyde branch is not yet ready. 

if you're planning to have the dots for hyde try to follow the instructions given on that error.

BTW, you need to reboot after. 

Your old configurations will be on the backup directory. 

I can't promise a smooth transition because I don't have any control on what certain branch of Hydprdots/hyde you got on your device.  

I recommend a fresh installed. 
``` Hyde-install ``` Should do the work 

I will warn you that Hyde and Hyde-cli are both on dev branches, expect any breaking changes.

**Comment by kRHYME7** [comment]
One more thing please do and update, I tried to fix the error for wallbash ``` yay -Sy hyde-cli-git ```

**Comment by Oskar-Idland** [comment]
I do not know if this is equivalent on NixOS which you seem to be using judging by your PATH. I got the same error, and when looking at line 173 in [Hyde-install](https://github.com/kRHYME7/Hyde-cli/blob/master/Hyde-install), you see a check for the `globalcontrol.sh` script, which should be located at `~/.local.share/bin/`. Either the location is missing from your PATH variable (was the case for me), or you do not have the file at all. I do not know if the locations are the same on NixOS though, if that is what you use.

**Comment by kRHYME7** [comment]
Yeah, the script mainly needed the  ``` ~/.local.share/bin/globalcontrol.sh  ``` it should be installed if you  run ``` Hyde-install ```  (the same as ./install.sh ). 

Now some Hyde command needs to access the Clone directory which the CLI does't know unless you installed using the CLI or run ``` Hyde-install -d /path/to/clone -l ``` -d is your clone directory and -l means ' link ' the Clone so Hyde-CLI remembers the clone directory.

**Comment by kRHYME7** [comment]
Thanks for actually testing this!
