### ISSUE TITLE
How do I toggle wallbash for specific applications in Hyde?

### ISSUE THREAD

**Issue by Radrahil** [kRHYME7/Hyde-cli#28]
Previously, I could do stuff like Hyprdots wallbash kitty 0. How do I do that now?

**Comment by kRHYME7** [comment]
``` Hyde wallbash ``` See instructions

**Comment by Radrahil** [comment]
Yeah, but previously, I could do that for specific applications. This is no longer the case.

**Comment by kRHYME7** [comment]
output for this ? ```  cat ~/.config/hyde/hyde.conf ``` 

I think the latest commits move the variable to here

**Comment by kRHYME7** [comment]
Okay fixed https://github.com/kRHYME7/Hyde-cli/commit/effd43a2aea2d1a4c59e1e3fd3b016c4f57ddcf2

**Comment by Radrahil** [comment]
Oh, ok. I'll just run Hyde upgrade in a couple days then.
