### ISSUE TITLE
Having issue using hyde-install on a pure arch install

### ISSUE THREAD

**Issue by legendboyAni** [kRHYME7/Hyde-cli#30]
Well i installed pure arch with just base pkgs and have no nothing else no de no wm no nothing extra and installed hyde using paru, and when i run Hyde-install it cloned everything but when it asks for branch i sellected hyde branch and then i got this error that is showen in the image
![Screenshot_20240411-161307~2](https://github.com/kRHYME7/Hyde-cli/assets/115929231/fdf12688-cbc3-466e-a1f4-b5f9ea6b1528)

**Comment by legendboyAni** [comment]
There is no themes folder in .cache /hypr/Hyde-Clone/Configs/.config/hyde/ why it's looking the themes there and this script restarts sddm.service but that is not installed in pure arch which mean in docs it should tell that sddm is a requirement and will not get auto installed so we have to install it on our own

**Comment by kRHYME7** [comment]
Thanks for the detailed input, 

will fix this soon, we just need to relink the CLI to main.

**Comment by kRHYME7** [comment]
fixed https://github.com/kRHYME7/Hyde-cli/commit/ad2d5135b3ba928ec463477ceaec6b751731ad1c
