### ISSUE TITLE
Sourcing hyde.meta failed

### ISSUE THREAD

**Issue by Enigma1309** [kRHYME7/Hyde-cli#31]
![image](https://github.com/kRHYME7/Hyde-cli/assets/94917588/bd8dd08a-999d-46ce-bc5f-633800b8d08d)

Recently did a clean install but still it's showing the same error, i've also tries `Hyde-install` but it don't work

**Comment by kRHYME7** [comment]
can you try to rerun it again? updated the the cli? anything that might be helpful

**Comment by Enigma1309** [comment]
tried it too but it doesn't work :(

**Comment by Enigma1309** [comment]
here are content's of my ~/.cache/hyde
![image](https://github.com/kRHYME7/Hyde-cli/assets/94917588/96b259c0-a7b4-4c3f-81c3-6c0a60f96c26)

**Comment by kRHYME7** [comment]
Please maybe a SS of the error?

**Comment by Enigma1309** [comment]
![image](https://github.com/kRHYME7/Hyde-cli/assets/94917588/d610bd6c-c1eb-4d6c-b937-b04a5f31bec6)
no command seems to execute

**Comment by kRHYME7** [comment]
``` Hyde-install --link ``` 

returns nothing?

**Comment by Enigma1309** [comment]
okay it worked after update
