### ISSUE TITLE
install: sddm access denied

### ISSUE THREAD

**Issue by RAprogramm** [kRHYME7/Hyde-cli#33]
![240413_06h04m19s_screenshot](https://github.com/kRHYME7/Hyde-cli/assets/70325462/4a58846e-5b63-49c7-b92f-36afbe5f4431)

**Comment by kRHYME7** [comment]
![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/b7a09c56-c1a1-4ab8-acdf-9dfcd960b7a7)
 It is to restart sddm so that it will reload everything after install. Probably will add a notice to this.
 

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/7280a779-07e3-4010-84c1-66ed8e989047)

 BTW those errors are very unlikely to happen. did you use an older config?

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/059fb692-c507-404d-bc80-f2a6c2b011dd)

This branch is probably very outdated too because we are not supporting vscode theme extensions anymore.

**Comment by RAprogramm** [comment]
> ![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/b7a09c56-c1a1-4ab8-acdf-9dfcd960b7a7)
>  It is to restart sddm so that it will reload everything after install. Probably will add a notice to this.
>  
> 
> ![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/7280a779-07e3-4010-84c1-66ed8e989047)
> 
>  BTW those errors are very unlikely to happen. did you use an older config?
> 
> ![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/059fb692-c507-404d-bc80-f2a6c2b011dd)
> 
> This branch is probably very outdated too because we are not supporting vscode theme extensions anymore. 
>  
>  

If I had hyprdots already installed and working, I just downloaded Hyde-ctl from aur via yay and did Hyde-install

**Comment by kRHYME7** [comment]
output for ``` Hyde-version ``` ?

**Comment by RAprogramm** [comment]
![240413_09h49m09s_screenshot](https://github.com/kRHYME7/Hyde-cli/assets/70325462/473173af-b765-4627-b815-b6b245784ae8)

**Comment by kRHYME7** [comment]
I see the branch it follow is the older one

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/11b1ce02-b373-44a4-aa66-3ba73399bd56)



Can you please switch is to main? 

``` Hyde branch ``` 

Will add back the check (removed it because to transition to main)

**Comment by kRHYME7** [comment]
Also added the option to set branch on Fresh install v0.5.2.r5.6cc4f66%

**Comment by RAprogramm** [comment]
Now it works good. And themes are patching correctly.
Thank you very much!!!

---

i think little bit not intuitive interface (fzf) when installing, so i create an issue later)

**Comment by kRHYME7** [comment]
> i think little bit not intuitive interface (fzf) when installing, so i create an issue later) 

Yes please, to compensate on this I just tried to verbose all (I knew some will ignore it )

**Comment by kRHYME7** [comment]
If some of the scripts are ready I will expose a fzf file which has variables with fzf flags that the script can source. 

If this is possible, we can modify the eye candies for fzf and be isolated from the scripts. I hope this is possible
