### ISSUE TITLE
[BUG] theme selector and wallpaper selector looks odd

### ISSUE THREAD

**Issue by itsmenewbie03** [kRHYME7/Hyde-cli#34]
After the pulling the latest changes both the theme and wallpaper looks a bit odd (looks bigger and out of scale)
![image](https://github.com/kRHYME7/Hyde-cli/assets/89230263/1ebc9028-76d8-4175-bf99-5f0c37143721)
![image](https://github.com/kRHYME7/Hyde-cli/assets/89230263/1963dd2f-e43a-47e8-8cc1-87c41de32cb5)

### Extra xD
The shortcut `Super + R` is not working anymore, or am I hallucinating that it existed xD

**Comment by kRHYME7** [comment]
Hey this issue is in the Hyde repo.

 I don't control the scripts inside .local/share/bin

Try to scale it first though.

inside ~/.config/hyde/hyde.conf

add line

``` rofiScale=8 ``` Try changing this value 

also dunno about the keybind, See the README the keybindings are there.

**Comment by kRHYME7** [comment]
https://github.com/prasanthrangan/hyprdots/issues/1323

Let's discuss this in a single thread.
