### ISSUE TITLE
Hyde-cli as general Hyprland Dots manager

### ISSUE THREAD

**Issue by dieBakterie** [kRHYME7/Hyde-cli#41]
Is it possible to add additional folders and files to manage with Hyde-cli?

**Comment by kRHYME7** [comment]
Huh?

**Comment by dieBakterie** [comment]
It's no issue with Hyde-cli so i closed it

**Comment by kRHYME7** [comment]
Ah, I see, yes you can add it inside of ` ./restore.cfg.lst ` be sure to make the files or dirs existed.

**Comment by kRHYME7** [comment]
@dieBakterie  ` Hyde restore Clone  /patch/to/custom/clone ` or link the custom clone to like ` Hyde restore link ` 

Now that clone directory is yours, and you can always run git pull without any issues. As long as no merge conflicts. (learn git for this )

Helpful note is  when you add files inside a Clone directory it is fine to run git pull. No changes will happen to your new files as long as it is not a conflict. git is huge so please learn a little bit of it then you'll love open source more! HAHAHA 


Sorry for not understanding the question so well.

**Comment by kRHYME7** [comment]
So yes you can.  Will close this okay?

**Comment by dieBakterie** [comment]
> Ah, I see, yes you can add it inside of ` ./restore.cfg.lst ` be sure to make the files or dirs existed. 

With existed you mean that they're in the cloned repo right?

**Comment by kRHYME7** [comment]
> With existed you mean that they're in the cloned repo right?

Yes that's how it works.  It will be skipped if it is not in the Clone directory
