### ISSUE TITLE
feature: Add a toggle mode for power

### ISSUE THREAD

**Issue by rubiin** [kRHYME7/Hyde-cli#43]
Adding a toggle mode for power saver to quickly turn on power save.

doing a little alias thing for now
```sh
power-save() {
	if [[ $1 == "on" ]]; then
		Hyde power save -a -ba -b -o
	else
		Hyde power reset
	fi
}

```

**Comment by rubiin** [comment]
the toggle doesnt have to take an input , this was a hacky attempt .

**Comment by kRHYME7** [comment]
Done

**Comment by rubiin** [comment]
cool
