### ISSUE TITLE
Add ability to edit/manage control file

### ISSUE THREAD

**Issue by Enigma1309** [kRHYME7/Hyde-cli#49]
continuation of https://github.com/kRHYME7/Hyde-cli/discussions/12#discussioncomment-9332131

- command to edit and utilize the potential of `~/.cache/hyde/manage_cfg.lst` for managing the user level customization

**Comment by kRHYME7** [comment]
` Hyde control Config `

**Comment by kRHYME7** [comment]
Adding user configuration that is in the Clone Dir is still not supported as it will borke some configs. Better to fork the repo locally and maintain it locally.

**Comment by Enigma1309** [comment]
okay
