### ISSUE TITLE
bug: Cursor seems to be broken

### ISSUE THREAD

**Issue by drnikos** [kRHYME7/Hyde-cli#62]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

latest

### Operating system/version

Arch

### Describe the bug

I ran Hyde theme patch after installing hyprdots from the github repo, I selected all themes but after patching, the cursor seems broken. It's huge and not propely themed in some apps

https://github.com/kRHYME7/Hyde-cli/assets/153459342/ca122d1a-2a76-416d-a604-8db0409a5386

### Steps To Reproduce

Simply use Hyde theme patch

### Expected Behavior

expected the cursor to be normal I guess

**Comment by kRHYME7** [comment]
see if the behavior is persistent in all themes.  Your using gruvbox which has a different  cursor pack. This CLI is not related to the theme though

**Comment by kRHYME7** [comment]
see if the behavior is persistent in all themes.  Your using gruvbox which has a different  cursor pack. This CLI is not related to the theme though 

Also Check this out https://github.com/prasanthrangan/hyprdots/issues/1517

**Comment by drnikos** [comment]
Ok.
