### ISSUE TITLE
bug:sddm config never generates with Hyde-Install

### ISSUE THREAD

**Issue by jenil1122** [kRHYME7/Hyde-cli#72]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

hyde-cli-git-v0.5.0.r43.7929e50-1

### Operating system/version

Arch

### Describe the bug

whenever i Try to Install Sddm with Hyde or Select It during Hyde Installation with Hyde-Install it never works. i Need to manually create sddm.conf.d folder inside /etc and then run Hyde to install sddm . Base installation of arch with sddm does not generate /etc/sddm.conf.d folder

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by kRHYME7** [comment]
Any terminal outputs, other than never works? 


> /etc/sddm.conf.d/ 

You mean at fresh install (but with sddm package already insatalled ) this folder is not created by default?

**Comment by jenil1122** [comment]
yes

**Comment by kRHYME7** [comment]
@jenil1122  do ` Hyde sddm theme ` works?

**Comment by kRHYME7** [comment]
@jenil1122  So you mean we need to create the folder first before populating the Dots?Right?

**Comment by jenil1122** [comment]
> @jenil1122 do `Hyde sddm theme` works?

After enabling and starting sddm i got default sddm login theme . Then i tried  with  Hyde-cli it gave me same error of failed to copy directory not found . After manually creating folder hyde cli installed the sddm theme with no errors

**Comment by jenil1122** [comment]
> @jenil1122 So you mean we need to create the folder first before populating the Dots?Right?

Yes
